# Generated by Django 4.2.23 on 2025-08-31 17:24

from django.db import migrations
import oris.models


class Migration(migrations.Migration):

    dependencies = [
        ('oris', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='utilisateur',
            managers=[
                ('objects', oris.models.CustomUserManager()),
            ],
        ),
    ]
